EvolutionaryAlgorithmsFinalReportGroup.pdf: EvolutionaryAlgorithmsFinalReportGroup.tex
	pdflatex  EvolutionaryAlgorithmsFinalReportGroup
	bibtex EvolutionaryAlgorithmsFinalReportGroup
	pdflatex EvolutionaryAlgorithmsFinalReportGroup
	pdflatex EvolutionaryAlgorithmsFinalReportGroup

test:
	open EvolutionaryAlgorithmsFinalReportGroup.pdf

clean:
	rm *.bbl *.dvi *.aux *.log *.blg *.pdf

edit:
	vim EvolutionaryAlgorithmsFinalReportGroup.tex

